name: chat_bot
description: "A customizable chatbot built on OpenAI's GPT API, enabling personalized conversational experiences."
version: 1.0.1

homepage: https://solid-clone-334117.firebaseapp.com/ 
repository: https://github.com/anthonyR012/chat_bot_package 

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  dio: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:



