name: chat_bot
description: "A customizable chatbot built on OpenAI's GPT API, enabling personalized conversational experiences."
version: 1.1.1

repository: https://github.com/anthonyR012/chat_bot_package 

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  emoji_picker_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.12
  

flutter:



